### ISSUE TITLE
Support for the Rollbar Person parameter

### ISSUE THREAD

**Issue by ma314smith** [stvp/roll#2]
I'd like to be able to pass person data through the Logrus Rollbar hook (https://github.com/heroku/rollrus), which depends on this package.  Would you be open to adding support for the person parameter (see the Data Format section here: https://rollbar.com/docs/api/items_post/).  If so, I can submit a PR.

**Comment by bpo** [comment]
@ma314smith yes, definitely open to adding person support (if you're still interested – sorry for the late reply). We'll continue the discussion on your PR when you open it. Thanks!
