### ISSUE TITLE
Reconsider errorClass implementation

### ISSUE THREAD

**Issue by hut8** [stvp/roll#3]
Hey. Thanks for this package.

I noticed the implementation of errorClass here:
https://github.com/stvp/roll/blob/master/client.go#L204

I've been having an issue with the handling of strings as errors. Today, I forgot an `if` statement (dumb mistake) and caused an error that only happens on production (obviously, my fault), but it generated quite a few identical errors with different error strings. I'm trying to stay on the free tier with this project since it's a hobby project, and in a minute or two it racked up like 2500+ events (more than half for the month), flooded my inbox and our project's Slack channel.

In general, aside from my dumb typo, I think it would be more useful if some other method were used instead of the string checksum trick. For example, timeouts generate this message:

```
write tcp 127.0.0.1:5000->127.0.0.1:33893: write: broken pipe
```

Here's the full raw JSON that was sent to rollbar:

https://gist.github.com/hut8/80557e834856756f6b98

Before I jump into coding and open a PR, what are your thoughts on this? My first thought was that if it really is a string, then errorClass could simply return "string". Or, alternatively, it could base a checksum or something off of the stack trace, or maybe even allow you to specify the class in some other way.

**Comment by bpo** [comment]
@hut8, sorry for the late follow-up here. I think #8 resolves your problem – can you re-open and provide more detail if not?
