### ISSUE TITLE
master of roll, fails to compile

### ISSUE THREAD

**Issue by apg** [stvp/roll#6]
``` bash
./stack.go:43: undefined: runtime.CallersFrames
```

**Comment by apg** [comment]
Hmm, this might just be because I haven't upgraded to 1.7.

**Comment by tysonmote** [comment]
Ah, yup: https://golang.org/doc/go1.7#runtime

Sorry about that! The docs don't call out the fact that that method was only recently added so I totally missed that. I'll make sure that 1.6 is supported.
