### ISSUE TITLE
Reconsider sending fingerprint to Rollbar

### ISSUE THREAD

**Issue by challiwill** [stvp/roll#7]
This library sets the `fingerprint` field when sending log messages to Rollbar (https://github.com/stvp/roll/blob/master/client.go#L142). This is probably often a good idea since there is more context lower down about where the error is coming from. However, for some cases this results in improper groupings that cannot be overwritten. The hierarchy for fingerprints is as follows (in descending priority): client provided, custom groupings from the UI, Rollbar calculated grouping. 

For example, we have an unmarshal error that includes the bytes from the message that was getting unmarshaled. When the fingerprint is calculated (https://github.com/stvp/roll/blob/master/stack.go#L64) with the title string - in this case the error message - this results in separate fingerprints for errors coming from the same source. We want these errors to be grouped in Rollbar, and could use a custom grouping to do this, but cannot because we are unable to overwrite the client provided fingerprint. 

Would you consider a PR to do one of the following:
1 - No longer use the title in the hash (probably the easiest, just remove https://github.com/stvp/roll/blob/master/stack.go#L66)
2 - Remove setting the fingerprint in the client
3 - Provide an option to log without a custom fingerprint
4 - Something else that you suggest?

Based on the function description, Option 1 seems to be the best. This way we guarantee that the hash is always the same for the same filename, method name, and line number.

**Comment by challiwill** [comment]
I opened a PR for option number 1 that I proposed above. Please let me know your thoughts. f you'd like to close this issue and use the PR for a conversation that'd be great too.

**Comment by bpo** [comment]
Fixed with #8 and ca202b60b2601abe3e2e6a948a12b1b856badf6c. Thanks!
